-- Migration 0002: create `stages` table
CREATE TABLE IF NOT EXISTS `stages` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `order_index` INT UNSIGNED NOT NULL DEFAULT 0,
  `color` VARCHAR(20) NOT NULL DEFAULT '#6366f1',
  `is_won` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_lost` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_stages_order` (`order_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;